#!/usr/bin/env bash
# Download the PDFs for the CSE 210B candidate reading list (../readings.md)
# into this directory, named "<Title> - <Authors>.pdf".
#
# Usage:  cd papers && ./download.sh
#         ./download.sh --numbered   # prefix each file with its entry
#                                    # number in readings.md ("07 - ...")
#                                    # (or use ./download-num.sh)
# Re-running skips files that already exist. Requires curl.
#
# Notes:
#  - Entries 6 (CHI) uses the ACM DL and may require institutional access
#    (UCSC's subscription covers it via campus network/VPN).
#  - Entry 7 downloads the arXiv preprint ("Productivity Assessment of
#    Neural Code Completion"), the open version of the CACM article.
#  - Entry 27 downloads the arXiv preprint of the FMCAD 2024 "Loopy" paper.
#  - Entry 47 (AlphaProof) is an open-access Nature paper.

set -u

NUMBERED=0
[ "${1:-}" = "--numbered" ] && NUMBERED=1
ENTRY=0   # entry number in readings.md; download() calls below are in order

download() {
  local url="$1" file="$2"
  ENTRY=$((ENTRY + 1))
  if [ "$NUMBERED" = 1 ]; then
    file="$(printf '%02d' "$ENTRY") - $file"
  fi
  if [ -s "$file" ]; then
    echo "SKIP (exists): $file"
    return 0
  fi
  echo "GET  $file"
  if curl -fsSL --retry 3 --retry-delay 2 -A "Mozilla/5.0 (course-reader)" \
       -o "$file" "$url"; then
    # Sanity check: a real PDF, not an HTML error page
    if head -c4 "$file" | grep -q "%PDF"; then
      echo "OK   $file"
    else
      echo "WARN not a PDF (kept for inspection): $file  <- $url"
    fi
  else
    echo "FAIL $url"
    rm -f "$file"
  fi
}

a() { download "https://arxiv.org/pdf/$1" "$2"; }

## 1. Foundations: LLMs for code generation
a 2107.03374 "Evaluating Large Language Models Trained on Code - Chen et al.pdf"
a 2203.07814 "Competition-Level Code Generation with AlphaCode - Li et al.pdf"
a 2305.01210 "Is Your Code Generated by ChatGPT Really Correct - Liu et al.pdf"
a 2308.10620 "Large Language Models for Software Engineering - A Systematic Literature Review - Hou et al.pdf"

## 2. Human factors and productivity
a 2206.15000 "Grounded Copilot - How Programmers Interact with Code-Generating Models - Barke, James, Polikarpova.pdf"
download "https://dl.acm.org/doi/pdf/10.1145/3491101.3519665" \
  "Expectation vs Experience - Evaluating the Usability of Code Generation Tools - Vaithilingam, Zhang, Glassman.pdf"
a 2205.06537 "Measuring GitHub Copilot's Impact on Productivity (Productivity Assessment of Neural Code Completion) - Ziegler et al.pdf"
a 2507.09089 "Measuring the Impact of Early-2025 AI on Experienced Open-Source Developer Productivity - Becker et al.pdf"

## 3. Coding agents and large-scale software engineering
a 2310.06770 "SWE-bench - Can Language Models Resolve Real-World GitHub Issues - Jimenez et al.pdf"
a 2405.15793 "SWE-agent - Agent-Computer Interfaces Enable Automated Software Engineering - Yang et al.pdf"
a 2404.05427 "AutoCodeRover - Autonomous Program Improvement - Zhang et al.pdf"
a 2407.01489 "Agentless - Demystifying LLM-based Software Engineering Agents - Xia et al.pdf"
a 2305.18584 "Coeditor - Leveraging Repo-level Diffs for Code Auto-editing - Wei, Durrett, Dillig.pdf"

## 4. LLM-powered testing, fuzzing, debugging, and repair
a 2302.06527 "An Empirical Evaluation of Using Large Language Models for Automated Unit Test Generation - Schäfer, Nadi, Eghbali, Tip.pdf"
a 2403.16218 "CoverUp - Effective High Coverage Test Generation for Python - Altmayer Pizzorno, Berger.pdf"
a 2212.14834 "Large Language Models Are Zero-Shot Fuzzers - Deng et al.pdf"
a 2308.04748 "Fuzz4All - Universal Fuzzing with Large Language Models - Xia et al.pdf"
a 2403.16354 "ChatDBG - Augmenting Debugging with Large Language Models - Levin et al.pdf"
a 2304.00385 "Automated Program Repair via Conversation (ChatRepair) - Xia, Zhang.pdf"

## 5. Security and trust of AI-generated code
a 2108.09293 "Asleep at the Keyboard - Assessing the Security of GitHub Copilot's Code Contributions - Pearce et al.pdf"
a 2211.03622 "Do Users Write More Insecure Code with AI Assistants - Perry et al.pdf"
a 2406.10279 "We Have a Package for You - A Comprehensive Analysis of Package Hallucinations - Spracklen et al.pdf"
a 2504.15254 "CRUST-Bench - A Comprehensive Benchmark for C-to-safe-Rust Transpilation - Khatry et al.pdf"

## 6. From natural language to specifications and invariants
a 2310.01831 "Can LLMs Transform Natural Language Intent into Formal Method Postconditions - Endres et al.pdf"
a 2401.08807 "SpecGen - Automated Generation of Formal Program Specifications via LLMs - Ma et al.pdf"
a 2303.04864 "nl2spec - Interactively Translating Natural Language to Temporal Logics - Cosler et al.pdf"
a 2311.07948 "Leveraging LLMs for Program Verification (Loopy) - Kamath et al.pdf"
a 2310.09342 "Ranking LLM-Generated Loop Invariants for Program Verification - Chakraborty et al.pdf"
a 2310.04870 "Lemur - Integrating Large Language Models in Automated Program Verification - Wu, Barrett, Narodytska.pdf"
a 2305.09656 "SatLM - Satisfiability-Aided Language Models Using Declarative Prompting - Ye, Chen, Dillig, Durrett.pdf"

## 7. Verified code generation: Dafny, Verus, and F*
a 2402.00247 "Towards AI-Assisted Synthesis of Verified Dafny Methods - Misu, Lopes, Ma, Noble.pdf"
a 2310.17807 "Clover - Closed-Loop Verifiable Code Generation - Sun, Sheng, Padon, Barrett.pdf"
a 2411.15143 "dafny-annotator - AI-Assisted Verification of Dafny Programs - Poesia, Loughridge, Amin.pdf"
a 2409.13082 "AutoVerus - Automated Proof Generation for Rust Code - Yang et al.pdf"
a 2412.06176 "AlphaVerus - Bootstrapping Formally Verified Code Generation - Aggarwal, Parno, Welleck.pdf"
a 2405.01787 "Towards Neural Synthesis for SMT-Assisted Proof-Oriented Programming - Chakraborty et al.pdf"
a 2406.03003 "Verified Code Transpilation with LLMs (LLMLift) - Bhatia et al.pdf"
a 2505.23135 "Verina - Benchmarking Verifiable Code Generation - Ye et al.pdf"

## 8. LLMs and interactive theorem proving
a 2303.04910 "Baldur - Whole-Proof Generation and Repair with Large Language Models - First, Rabe, Ringer, Brun.pdf"
a 2210.12283 "Draft, Sketch, and Prove - Guiding Formal Theorem Provers with Informal Proofs - Jiang et al.pdf"
a 2306.15626 "LeanDojo - Theorem Proving with Retrieval-Augmented Language Models - Yang et al.pdf"
a 2310.04353 "An In-Context Learning Agent for Formal Theorem-Proving (COPRA) - Thakur et al.pdf"
a 2409.14274 "Proof Automation with Large Language Models (PALM) - Lu, Delaware, Zhang.pdf"
a 2412.14063 "Rango - Adaptive Retrieval-Augmented Proving for Automated Software Verification - Thompson et al.pdf"
a 2503.24036 "Automated Discovery of Tactic Libraries for Interactive Theorem Proving (TacMiner) - Xin et al.pdf"

## 9. Frontier: formal mathematics and what comes next
a 2205.12615 "Autoformalization with Large Language Models - Wu et al.pdf"
download "https://www.nature.com/articles/s41586-025-09833-y.pdf" \
  "Olympiad-Level Formal Mathematical Reasoning with Reinforcement Learning (AlphaProof) - Hubert et al.pdf"
a 2502.07640 "Goedel-Prover - A Frontier Model for Open-Source Automated Theorem Proving - Lin et al.pdf"
a 2412.16075 "Formal Mathematical Reasoning - A New Frontier in AI - Yang et al.pdf"

echo
echo "Done. $(ls -1 *.pdf 2>/dev/null | wc -l) PDFs present."
